# syntax=docker/dockerfile:1.3-labs
FROM rocker/shiny:3.6.3

MAINTAINER Kristian Peters <kpeters@ipb-halle.de>

LABEL Description="MetFamily Base Image with dependencies."

RUN apt-get -y --allow-releaseinfo-change update && apt-get -y install \
  netcdf-bin libnetcdf-dev libdigest-sha-perl libigraph0-dev \
  xorg-dev libglu1-mesa-dev freeglut3-dev libgomp1 libxml2-dev gcc g++ libcurl4-gnutls-dev libssl-dev gdebi-core libharfbuzz-dev libfribidi-dev libtiff5-dev

ENV NETCDF_INCLUDE=/usr/include
RUN echo 'sanitize_errors off;disable_protocols xdr-streaming xhr-streaming iframe-eventsource iframe-htmlfile;' >> /etc/shiny-server/shiny-server.conf

COPY <<EOF /root/.Rprofile
local({
  r <- getOption(\"repos\")
  r[\"CRAN\"] <- \"https://packagemanager.posit.co/cran/2020-04-23/\"
  options(repos=r)
})
EOF

ADD DESCRIPTION /tmp/MetFamily/DESCRIPTION
RUN R -e 'options(warn=2) ; install.packages("devtools")'
RUN R -e 'options(warn=2) ; install.packages("XML")'
RUN R -e 'options(warn=2) ; install.packages("MALDIquant")'
RUN R -e 'options(warn=2) ; install.packages("FactoMineR")'
RUN R -e 'library(devtools); options(warn=2) ; install_deps("/tmp/MetFamily")'

WORKDIR /srv/shiny-server
