FROM rocker/shiny:3.6.3

MAINTAINER Kristian Peters <kpeters@ipb-halle.de>

LABEL Description="MetFamily Base Image with dependencies."

RUN apt-get -y update && apt-get -y install \
  netcdf-bin libnetcdf-dev libdigest-sha-perl libigraph0-dev \
  xorg-dev libglu1-mesa-dev freeglut3-dev libgomp1 libxml2-dev gcc g++ libcurl4-gnutls-dev libssl-dev gdebi-core

ENV NETCDF_INCLUDE=/usr/include
RUN echo 'sanitize_errors off;disable_protocols xdr-streaming xhr-streaming iframe-eventsource iframe-htmlfile;' >> /etc/shiny-server/shiny-server.conf

ADD binder /tmp
RUN R -e "source('/tmp/install.R')"

WORKDIR /srv/shiny-server


