# syntax=docker/dockerfile:1.3-labs
FROM rocker/shiny:4.4
#FROM rocker/shiny:4.4

LABEL maintainer="Steffen Neumann <sneumann@ipb-halle.de>"
LABEL Description="MetFamily Base Image with dependencies."

## Older base images might need libigraph0-dev instead of libigraph-dev 
RUN apt-get -y --allow-releaseinfo-change update && apt-get -y install \
  netcdf-bin libnetcdf-dev libdigest-sha-perl libigraph-dev \
  xorg-dev libglu1-mesa-dev freeglut3-dev libgomp1 libxml2-dev gcc g++ libcurl4-gnutls-dev libssl-dev gdebi-core libharfbuzz-dev libfribidi-dev libtiff5-dev

ENV NETCDF_INCLUDE=/usr/include
RUN echo 'sanitize_errors off;disable_protocols xdr-streaming xhr-streaming iframe-eventsource iframe-htmlfile;' >> /etc/shiny-server/shiny-server.conf

## The following Rprofile allows to use CRAN snapshots
## (The HERE document COPY <<EOF requires syntax=docker/dockerfile:1.3-labs)
## We have tested the following combinations of FROM and CRAN:
## rocker/shiny:4.3.2
## rocker/shiny:3.6.3	https://packagemanager.posit.co/cran/2020-04-23/
## rocker/shiny:4.0.5	https://packagemanager.posit.co/cran/2021-03-01/
## rocker/shiny:4.3.2	https://packagemanager.posit.co/cran/2023-12-01/

## COPY <<EOF /root/.Rprofile
## local({
##   r <- getOption(\"repos\")
##   r[\"CRAN\"] <- \"https://packagemanager.posit.co/cran/2021-03-01/\"
##   options(repos=r)
## })
## EOF

## Temporarily disable gcc choking on "error: format not a string literal and no format arguments"
#RUN sed -i -e 's/-Werror=format-security//g' /usr/local/lib/R/etc/Makeconf

ADD DESCRIPTION /tmp/MetFamily/DESCRIPTION
RUN R -e 'options(warn=2) ; install.packages(c("devtools", "BiocManager"))'
RUN R -e 'library(devtools); options(warn=2) ; install_deps("/tmp/MetFamily", repos=BiocManager::repositories())'

WORKDIR /srv/shiny-server
