
install.packages("devtools")
library("devtools")
install.packages("BiocManager")

install.packages("shiny")
devtools::install_github("rstudio/htmltools")
install.packages("shinyjs")
install.packages("DT")
install.packages("colourpicker")
install.packages("shinyBS")

BiocManager::install("mzR")
BiocManager::install("xcms")
BiocManager::install("mixOmics")
BiocManager::install("pcaMethods")

install.packages("FactoMineR")
install.packages("matrixStats")
install.packages("Matrix")
install.packages("stringi")
install.packages("slam")
install.packages("knitr")
install.packages("cba")
install.packages("squash")
install.packages("plotrix")
install.packages("RColorBrewer")
