
install.packages("devtools")
library("devtools")
source("https://bioconductor.org/biocLite.R")

install.packages("shiny")
devtools::install_github("rstudio/htmltools")
install.packages("shinyjs")
install.packages("DT")
install.packages("colourpicker")
install.packages("shinyBS")
biocLite("mzR")
biocLite("xmcs")
install.packages("FactoMineR")
install.packages("mixOmics")
biocLite("pcaMethods")
install.packages("matrixStats")
install.packages("Matrix")
install.packages("tools")
install.packages("stringi")
install.packages("slam")
install.packages("knitr")
install.packages("cba")
install.packages("squash")
install.packages("plotrix")
install.packages("RColorBrewer")
